garden = ('ромашка', 'роза', 'одуванчик', 'ромашка', 'гладиолус', 'подсолнух', 'роза', )
meadow = ('клевер', 'одуванчик', 'ромашка', 'клевер', 'мак', 'одуванчик', 'ромашка', )
garden_set =set(garden)
meadow_set =set(meadow)
all_flowers = garden_set.union(meadow_set)
print("Все виды цветов:", all_flowers)
same_flowers = garden_set.intersection(meadow_set)
print("Цветы, которые растут и там и там :", same_flowers)
garden_only = garden_set.difference(meadow_set)
print("Цветы, которые растут в саду, но не растут на лугу:", garden_only)
meadow_only = meadow_set.difference(garden_set)
print("Цветы, которые растут на лугу, но не растут в саду:", meadow_only)
